---
resources:
- name: rabbitmq-cluster-migration-tool
  type: git
  source:
    uri: git@github.com:pivotal-cf/rabbitmq-cluster-migration-tool.git
    branch: master
    private_key: {{git-ssh-key}}

jobs:
- name: test
  plan:
  - get: rabbitmq-cluster-migration-tool
    trigger: true
  - task: run-test
    config:
      inputs:
      - name: rabbitmq-cluster-migration-tool
        path: src/github.com/pivotal-cf/rabbitmq-cluster-migration-tool
      platform: linux
      image: docker:///cflondonservices/london-services-ci-rabbitmq#stable
      run:
        path: src/github.com/pivotal-cf/rabbitmq-cluster-migration-tool/scripts/run_tests

